include(FindPackageHandleStandardArgs)

find_package(Ogg REQUIRED)

find_path(FLAC_INCLUDE_DIRS FLAC/stream_decoder.h)
find_library(FLAC_LIBRARIES NAMES FLAC)
find_package_handle_standard_args(FLAC DEFAULT_MSG FLAC_INCLUDE_DIRS FLAC_LIBRARIES )
mark_as_advanced(FLAC_INCLUDE_DIRS FLAC_LIBRARIES )

if( FLAC_FOUND AND NOT TARGET flac )
  add_library(flac STATIC IMPORTED GLOBAL)
  set_target_properties(flac PROPERTIES
    IMPORTED_LOCATION ${FLAC_LIBRARIES}
    INTERFACE_INCLUDE_DIRECTORIES "${FLAC_INCLUDE_DIRS};${Ogg_INCLUDE_DIRS}"
    INTERFACE_LINK_LIBRARIES "${Ogg_LIBRARIES}"
	)
endif()


find_path(FLACPP_INCLUDE_DIRS FLAC++/decoder.h)
find_library(FLACPP_LIBRARIES NAMES FLAC++)
find_package_handle_standard_args(FLACPP DEFAULT_MSG FLACPP_INCLUDE_DIRS FLACPP_LIBRARIES )
mark_as_advanced(FLACPP_INCLUDE_DIRS FLACPP_LIBRARIES )

if( FLACPP_FOUND AND NOT TARGET flacpp )
  add_library(flacpp STATIC IMPORTED GLOBAL)
  set_target_properties(flacpp PROPERTIES
    IMPORTED_LOCATION ${FLACPP_LIBRARIES}
    INTERFACE_INCLUDE_DIRECTORIES "${FLACPP_INCLUDE_DIRS};${FLAC_INCLUDE_DIRS};${Ogg_INCLUDE_DIRS}"
    INTERFACE_LINK_LIBRARIES "${FLAC_LIBRARIES};${Ogg_LIBRARIES}"
	)
endif()

