include(FindPackageHandleStandardArgs)

find_package(PkgConfig REQUIRED)

pkg_check_modules (GSTREAMERAPP REQUIRED gstreamer-app-1.0)
find_library(GSTREAMERAPP_LIBRARY NAMES gstapp-1.0)

find_package_handle_standard_args(GSTREAMERAPP DEFAULT_MSG GSTREAMERAPP_INCLUDE_DIRS GSTREAMERAPP_LIBRARY)
mark_as_advanced(GSTREAMERAPP_INCLUDE_DIRS GSTREAMERAPP_LIBRARY)


if( GSTREAMERAPP_FOUND )
	if( NOT TARGET GSTREAMERAPP::gstreamerapp )
    add_library(GSTREAMERAPP::gstreamerapp SHARED IMPORTED)
    set_target_properties(GSTREAMERAPP::gstreamerapp PROPERTIES
      IMPORTED_LINK_INTERFACE_LANGUAGES "C"
      IMPORTED_LOCATION ${GSTREAMERAPP_LIBRARY}
      INTERFACE_INCLUDE_DIRECTORIES "${GSTREAMERAPP_INCLUDE_DIRS}"
      INTERFACE_LINK_LIBRARIES "${GSTREAMERAPP_LIBRARY}"
    )
  endif()
endif()

