name: CI-Verification

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:

  linux-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -yq libboost-all-dev libgtest-dev libogg-dev libvorbis-dev libflac++-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run:  |
        git lfs pull -X \"\"
        ctest --verbose -C ${{env.BUILD_TYPE}} --timeout 900
  
  windows-build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        vcpkg install

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run:  |
        git lfs pull -X \"\"
        ctest --verbose -C ${{env.BUILD_TYPE}} --timeout 900
      
  macos-build:
    runs-on: macos-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Install dependencies
      run: brew install googletest boost vorbis-tools

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run:  |
        git lfs pull -X \"\"
        ctest --verbose -C ${{env.BUILD_TYPE}} --timeout 900
